# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: Build_Test
  strategy:
    matrix: 
      # Mac and Linux don't support localdb
      # Linux:
      #   matrixName: Ubuntu
      #   vmImageName: ubuntu-latest
      # Mac:
      #   matrixName: Mac
      #   vmImageName: macos-latest
      Windows:
        matrixName: Windows
        vmImageName: windows-latest
  pool:
    vmImage: $(vmImageName)

  variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'dotnet install'
    inputs:
      version: '2.2.104'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '**/*.csproj'
      publishTestResults: true